name: habitap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.0
  intl: ^0.20.2
  flutter_heatmap_calendar: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  csv: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/ic_launcher-web.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/Activity_Logo.svg
    - assets/lottie/streaks-anim.json
    - assets/lottie/arrow-anim.json
    - assets/icon/ic_launcher.png

  fonts:
    - family: 'Open Sans'
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
